language: python

python:
  - "2.7"

install:
  - pip install json-spec

script:
  - "bash -ex .travis-ci.sh"

matrix:
  fast_finish: true
  include:
    - env: TASK="nosetests"
    - env: TASK="karma"

notifications:
  irc:
    channels:
     - "chat.freenode.net#openlighting"
    on_success: change
    on_failure: change
