language: python

matrix:
  include:
    - python: "2.7"
      env: TASK="nosetests"
    - env: TASK="karma-firefox"
    - env: TASK="karma-phantomjs"

script: "bash -ex .travis-ci.sh"

notifications:
  irc:
    channels:
     - "chat.freenode.net#openlighting"
    on_success: change
    on_failure: change
