language: python

cache:
  - pip
  - npm

sudo: false

install:
  - pip install json-spec
  - npm install -g grunt-cli
  - npm install

matrix:
  include:
    - python: "2.7"
      env: TASK="nosetests"
    - env: TASK="karma"
    - env: TASK="js-lint"

script: "bash -ex .travis-ci.sh"

notifications:
  irc:
    channels:
     - "chat.freenode.net#openlighting"
    on_success: change
    on_failure: change
