language: python

python:
  - "2.7"

install:
  - pip install json-spec

script: nosetests

notifications:
  irc:
    channels:
     - "chat.freenode.net#openlighting"
    on_success: change
    on_failure: change
