application: "rdmprotocol"
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.html)
  static_files: \1
  upload: .*\.html

- url: /
  static_files: index.html
  upload: index.html

- url: /admin/.*
  script: admin.py
  login: required

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /(manufacturers|pid|pid_search)
  static_files: \1
  upload: (manufacturers|pid|pid_search)

- url: /foo
  script: main.py

builtins:
- datastore_admin: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^trunk/.*$
- ^BUILD*$
- ^DEBUG*$
- ^compiler.jar*$
