application: "rdmprotocol"
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.html)
  static_files: \1
  upload: .*\.html

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /
  static_files: index.html
  upload: index.html

- url: /admin/.*
  script: admin.py
  login: required

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

# common handlers
- url: /(index_info|manufacturers|product_categories)
  script: main.py

# PID search / display handlers
- url: /(pid|pid_search)
  script: main.py

# model search / display handlers
- url: /(model_search|model_info)
  script: main.py

# export handlers
- url: /(download|export_models|missing_models)
  script: export.py

- url: /admin
  script: admin.py

builtins:
- datastore_admin: on
- remote_api: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^trunk/.*$
- ^BUILD*$
- ^DEBUG*$
- ^compiler.jar*$
