application: "rdmprotocol-hrd"
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /(.*\.html)
  static_files: \1
  upload: .*\.html

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

# default landing page
- url: /
  script: model_handler.model_application

# page handlers
- url: /(contact|disclaimer)
  script: pages.pages_application

# model handlers
- url: /model/.*
  script: model_handler.model_application

# controller handlers
- url: /controller/.*
  script: controller_handler.controller_application

# pid handlers
- url: /pid/.*
  script: pid_handler.pid_application

# incoming data
- url: /incoming/.*
  script: incoming_handler.incoming_application

# export handlers
- url: /(download|export_controllers|export_models|export_personalities|index_info|manufacturers|missing_models)
  script: export.export_application

# Admin page
- url: /admin(/.*)?
  script: admin.admin_application
  login: required

- url: /tasks/(fetch_image|fetch_controller_image|rank_devices)
  script: tasks.tasks_application
  login: admin

builtins:
- appstats: on
- remote_api: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^trunk/.*$
- ^BUILD*$
- ^DEBUG*$
- ^compiler.jar*$
