application: "rdmprotocol"
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.html)
  static_files: \1
  upload: .*\.html

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /admin/.*
  script: admin.py
  login: required

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

# default landing page
- url: /
  script: model_handler.py

# page handlers
- url: /(contact|disclaimer)
  script: pages.py

# model handlers
- url: /model/.*
  script: model_handler.py

# controller handlers
- url: /controller/.*
  script: controller_handler.py

# pid handlers
- url: /pid/.*
  script: pid_handler.py

# export handlers
- url: /(download|export_controllers|export_models|export_personalities|index_info|manufacturers|missing_models)
  script: export.py

- url: /admin
  script: admin.py

- url: /tasks/(fetch_image|fetch_controller_image|rank_devices)
  script: tasks.py
  login: admin

builtins:
- appstats: on
- remote_api: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^trunk/.*$
- ^BUILD*$
- ^DEBUG*$
- ^compiler.jar*$
